POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "On the edge of the milkyway",
    "author": "Edward Normal",
    "url": "www.eppunormaali.fi",
    "likes": 200000
}